-- Recommendation: Do not edit this file, copy it to jc.spoon/.user/config_user.lua, and edit that file

return {
	-- JC Term scheme (alacritty + tmux, with auto positioning, snapping, and closing)
	-- term = true
}
