-- Recommendation: Do not edit this file, copy it to config_user.lua, and edit that file

return {
	-- JC Term scheme (alacritty + tmux, with auto positioning, snapping, and closing)
	-- term = false
}
